name: twitter_x_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  animated_splash_screen: ^1.0.1+2
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  numeral: ^2.0.1
  cupertino_icons: ^1.0.2
  simple_animations: ^5.0.2
  scroll_to_hide: ^2.0.1

dev_dependencies:
  http:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/lottie/
  - assets/lottie/twitter.json
  - assets/images/
